- name: Create anchore user
  user:
    name: anchore
    password: ''
    groups:
      - docker
      - sudo
    state: present
    shell: /bin/bash
    system: no
    createhome: yes

- name: Create directories for running Anchore and Docker compose
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ anchore_config_perms.owner }}'
    group: '{{ anchore_config_perms.group }}'
    mode: '{{ anchore_config_perms.mode }}'
  with_items:
    - '{{ anchore_remote_home }}'
    - '{{ anchore_remote_config_path }}'

- name: Copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: '{{ anchore_remote_home }}/{{ docker_remote_config_file }}'
    owner: '{{ anchore_config_perms.owner }}'
    group: '{{ anchore_config_perms.group }}'
    mode: '{{ anchore_config_perms.mode }}'

- name: Copy anchore_config_file
  template:
    src: config.j2
    dest: '{{ anchore_remote_config_path }}/{{ anchore_remote_config_file }}'
    owner: '{{ anchore_config_perms.owner }}'
    group: '{{ anchore_config_perms.group }}'
    mode: '{{ anchore_config_perms.mode }}'

- name: docker-compose via ansible docker_service
  docker_service:
    files:
      - "{{ docker_remote_config_file }}"
    project_src: "{{ anchore_remote_home }}"
    project_name: "bbs-services"
    pull: true
    state: present
    restarted: true
