---
# tasks file for provision/roles/ansible-anchore-jenkins
- name: System upgrade
  include: updatedpack.yml
- name: Installing requirement -  Docker and Docker-compose
  include: requirement.yml
- name: Configure docker
  include: docker.yml
