galaxy_info:
  author: Andrea Ceresoni
  description: Install Anchore https://anchore.com/ on a debian like machine
  company:


  license: BSD

  min_ansible_version: 2.4

  platforms:
   - name: Fedora
     versions:
     - all

  galaxy_tags: []

dependencies: []
