---
# vars file for provision/roles/hardening_debian

anchore_config_perms:
  owner: anchore
  group: anchore
  mode: '0740'

anchore_remote_home: '/home/anchore/aevolume'
anchore_remote_config_path: '/home/anchore/aevolume/config/'
anchore_remote_config_file: 'config.yaml'
docker_remote_config_file: 'docker-compose.yml'
