---
# vars file for provision/roles/hardening_debian

anchore_config_perms:
  owner: anchore
  group: anchore
  mode: '0640'

anchore_config_path: '/home/anchore/aevolume/config/'
anchore_config_file: 'config.yaml'


docker_remote_app_dir: '/home/anchore/docker-compose'

